#!/bin/bash

git config --global user.name 'github-actions'
git config --global user.email 'noreply@github.com'

echo 0
echo ${ACTION_KEY}
echo
echo 1
echo $ACTION_KEY

df -h
echo
#DEV="$(findmnt /mnt|awk '{print$2}'|grep '/dev/')"
#sudo swapoff -v /mnt/swapfile

sudo dd if=/dev/urandom of=/mnt/swap bs=1k count=10M status=progress || true
echo
ls -l /mnt/swap
echo

sudo chmod 600 /mnt/swap
sudo mkswap /mnt/swap
sudo swapon -v /mnt/swap
echo

swapon -v
echo

free -h
echo
df -Th

#git init
#git add README.md
#git commit -m "first commit"
#git branch -M main
#git remote add origin https://${ACTION_KEY}@github.com/ywzgt/action-progress.git
#git push -u origin main
