name: Build chromium
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest ]
        arch: [ x86, x64, arm, arm64 ]
        target: [ android, android_cromite, android_cromite_gms, linux, win ]
        exclude:
          - arch: arm
            target: win
          - arch: arm64
            target: win
        include:
          - os: windows-latest
            arch: arm64
            target: win
          - os: macos-13
            arch: x64
            target: mac
    runs-on: ${{ matrix.os }}
    permissions: write-all
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Download artifact ${{ matrix.arch }}
      uses: actions/download-artifact@v4
      with:
        name: mingw-ucrt-${{ matrix.arch }}
      continue-on-error: true

    - name: Upload to Releases
      if: env.TAG_VERSION
      uses: softprops/action-gh-release@master
      with:
        tag_name: ${{ env.TAG_VERSION }}
        body: monochrome ${{ env.TAG_VERSION }}
        files: apk/*
        fail_on_unmatched_files: true
        prerelease: false
    - name: Setup tmate ssh session
      if: failure() && github.event_name == 'workflow_dispatch'
      uses: mxschmitt/action-tmate@v3
    - run: uname -a; sudo dmesg -T
