name: Debugging with CI (Win)
on:
  workflow_dispatch:
jobs:
  ci:
    runs-on: windows-latest
    permissions: write-all
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: unzip
    - name: Start SSH via Ngrok
      if: ${{ always() }}
      run: curl -sL https://gist.github.com/$GITHUB_ACTOR/846376864e53a46bd610ae45d53e56a0/raw | bash
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_SSH_KEY: ${{ secrets.USER_SSH_KEY }}
    - name: Gh login
      run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token; gh auth setup-git; gh auth status
    - name: Don't kill instace
      run: while true; do date; df -Th; echo " "; sleep 500; head /dev/urandom > log; done
