name: Debugging with CI (Win)
on:
  workflow_dispatch:
jobs:
  ci:
    runs-on: windows-latest
    permissions: write-all
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: git unzip
    - name: Install SSH Server   # https://learn.microsoft.com/zh-cn/windows-server/administration/openssh/openssh_install_firstuse
      run: |
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
        Set-Service -StartupType Automatic -Name sshd
        Set-Service -StartupType Automatic -Name ssh-agent
        Start-Service sshd
        Start-Service ssh-agent
        Get-Service -Name sshd
        Get-Service -Name ssh-agent
        New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\msys64\usr\bin\bash.exe" -PropertyType String -Force
        bash -c "sed -i 's/^Match Group administrators$\|^\s*AuthorizedKeysFile __PROGRAMDATA__\/ssh\/administrators_authorized_keys/#&/' /C/ProgramData/ssh/sshd_config"
        Restart-Service sshd
      shell: pwsh

    - name: Start SSH via Ngrok
      if: ${{ always() }}
      run: curl -sL https://gist.github.com/$GITHUB_ACTOR/6161e69eb48330004144a59077559668/raw | bash
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_SSH_KEY: ${{ secrets.USER_SSH_KEY }}
    - name: Gh login
      run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token; gh auth setup-git; gh auth status
    - name: Don't kill instace
      run: while true; do date; df -Th; echo " "; sleep 500; head /dev/urandom | base64 > log; done

    - name: Setup tmate ssh session
      if: failure()
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
