name: Debugging with WIN
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup tmate ssh session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
    - name: Don't kill instace
      shell: C:\msys64\usr\bin\bash.exe {0}
      run: while true; do date; df -Th; free -h; echo " "; sleep 510; done
