name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect package manager
        id: detect
        continue-on-error: true
        run: |
          echo "cmd=run" >> $GITHUB_OUTPUT
          echo "command=install" >> $GITHUB_OUTPUT
          echo "command=update" >> $GITHUB_OUTPUT
          exit 1
      - name: Setup Node
        if: steps.detect.outputs.cmd == 'run'
        run: echo ${{ steps.detect.outputs.command }}
      - name: Setup Pages
        if: steps.detect.outputs.command == 'update'
        run: ls -la; echo ${{ steps.detect.outputs.command }}
