name: win
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Script
        run: |
          rem curl -LO https://raw.githubusercontent.com/WinMerge/sevenzip/master/BuildBin.vs2022.cmd
          curl -LO https://7-zip.org/a/7z2301-src.7z
          7z x 7z2301-src.7z
          rem BuildBin.vs2022.cmd
          rem set PATH=C:\msys64\usr\bin;%PATH%
          rem which 7z
          rem curl -LO https://commondatastorage.googleapis.com/chromium-browser-official/chromium-113.0.5672.93.tar.xz
          rem 7z x chromium-113.0.5672.93.tar.xz -oC:\
          rem cd /d c:
          rem 7z x chromium-113.0.5672.93.tar -oout
          rem md c:\chrome\chromium-113.0.5672.93
          rem ren c:\chrome\chromium-113.0.5672.93 src
          rem dir c:\chrome
          wmic pagefile list /format:list
          echo .
          wmic pagefileset Description=D:\pagefile.sys set InitialSize=1024,MaximumSize=4096
          echo .
          wmic pagefile list /format:list
        shell: cmd
      - uses: msys2/setup-msys2@v2
      - name: Run
        shell: msys2 {0}
        run: |
          uname -a
          wget https://github.com/ywzgt/llvm-gnu/releases/download/20240411-win/llvm-{i686,x86_64}.tar.xz
          tar xf llvm-i686.tar.xz
      - name: Setup tmate ssh session
        uses: mxschmitt/action-tmate@v3
