name: win
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Script
        run: |
          export PATH=/c/msys64/usr/bin:$PATH
          df -Tha
          printf 'Processor: '; cat /proc/cpuinfo|grep processor|wc -l
          cat /proc/cpuinfo|grep 'model name'|head -1
          cat /proc/meminfo | head; uname -a
          echo
          df -hTa
          echo
          ls -la
          echo
          SRCDEST="/c/chromium_sources_$ver"
          mkdir -vp "${SRCDEST}"

          ver="113.0.5672.116"
          git config --global advice.detachedHead false


          pushd ${SRCDEST} >/dev/null 2>&1

          echo '::Cloning depot_tools...'
          cmd /c git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo 'done.'

          ls -la

          popd >/dev/null 2>&1

          ls -la ${SRCDEST}/{depot_tools,}
	
        shell: C:\msys64\usr\bin\bash.exe -e {0}
