name: win
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Script
        run: |
          set PATH=C:\msys64\usr\bin;%PATH%
          timeout --help
          which timeout
          which tar
          which xz
          which split
          git clone --depth=1 -b 113.0.5672.116 https://chromium.googlesource.com/chromium/src
          dir
        shell: cmd
